### ISSUE TITLE
Hide "Table Mode: Off/On" in status bar as a setting

### ISSUE THREAD

**Issue by dLopreiato** [rpeshkov/vscode-text-tables#11]
The "Table Mode: Off/On" status at the bottom takes up a lot of room, and I don't use tables anywhere except in mark down. Is it possible to hide this status either by setting, or by file extension?

P.S.: I could attempt this myself via PR, but I want to make sure this is in alignment with your vision for this extension if I have to spend time coding it.

**Comment by rpeshkov** [comment]
Yes, that's great idea! I'm thinking about the name `text-tables.showStatus` for the setting and let it be enabled by default. For any particular project you'll be able to disable it through workspace settings. Of course it would be better to be able to set the setting for particular filename extension, but AFAIK VSCode allows to setup there only editor settings.

> P.S.: I could attempt this myself via PR, but I want to make sure this is in alignment with your vision for this extension if I have to spend time coding it.

That would be really great!

**Comment by rpeshkov** [comment]
@dLopreiato feature implemented. Will appear in the nearest update on marketplace.
