### ISSUE TITLE
Table Mode remains active after switching to other tabs

### ISSUE THREAD

**Issue by eisenchorn** [rpeshkov/vscode-text-tables#22]
After editing table in documentation I switched to other editor tab with some code and then <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> stopped working. It took some time to understand that problem was caused by enabled table mode.

Looks like Table Mode is enabled globally in vscode after its activation.

Is it possible to bind table mode to concrete editor tab, where it was activated or maybe to markdown files only?

If that global behavior is normal, maybe add setting, that makes table mode bound to single editor tab or markdown files only.

**Comment by rpeshkov** [comment]
Hi @eisenchorn. Totally agree, table mode should not be global. Each editor should have its state. I'll take a look on this issue and try to fix this behaviour in the nearest update. Or, if you want, you can make a PR for this. Contributions are welcome :)
