### ISSUE TITLE
How to quickly add underline of header ??

### ISSUE THREAD

**Issue by eromoe** [rpeshkov/vscode-text-tables#45]
The preview shows it adds underline of header  automatically.
But it took no effect on my PC,  I tried in or not in `table mode` , result same.

**Comment by rpeshkov** [comment]
Hi @eromoe,

In preview if you take a careful look on mode switching, you'll see that when header is added, Table mode is switched off, so you have plain text editing. Once header and starting of divider are added, I trigger `Text tables: Format under cursor` command and only after that I enter so called Table mode.

**Comment by robado** [comment]
I am also unable to do that thing in the preview. I first add the header and when going to next like and adding the divider it ads only - sign. So it doesn't do the same as in the preview. Also when I am adding a new line it jumps to the last cell and not the first.
