### ISSUE TITLE
Doesn't support ligatures

### ISSUE THREAD

**Issue by mackieburgess** [rpeshkov/vscode-text-tables#49]
If a ligature is used then the row misaligns left by one space.

**Comment by rpeshkov** [comment]
Hi @mackieburgess, I've tried to enable font with ligatures, but I wasn't able to reproduce the issue. Could you please provide more details on the issue? Also, screenshot would be really great.

**Comment by mackieburgess** [comment]
Hi @rpeshkov I'm using the .org file type with the vscode-org-mode extension.

image of error: https://imgur.com/a/hsj6LXK

**Comment by rpeshkov** [comment]
Ah, I see. Looks like you're using Menlo font, which has quite weird behavior on `fi` when ligatures are enabled. I have no idea how to overcome this issue.

Strange thing is that when I switch to Menlo font in iTerm, option for enabling ligatures is not even enabled, like the font doesn't support ligatures at all.

Regarding the ligatures itself, I can say that with i.e. Fira Code font everything works fine. Here's the screenshot:
![image](https://user-images.githubusercontent.com/701068/57574409-c5617580-7438-11e9-8d59-e53037c8cb60.png)

**Comment by rpeshkov** [comment]
P.S. Found similar issue with Menlo font in Blink.

https://github.com/blinksh/blink/issues/511

They fixed this issue by applying patch to their CSS styles here: https://github.com/blinksh/blink/commit/cde3f001018dbcab2c8ec8be8de97774615973f1
